/**
 * Comprehensive master catalog of major localities and postal areas covering Indian cities.
 * Rule 2: NO LOOPS. Pure functional lookup and composition.
 */
export const CITY_LOCALITIES_MAP: Record<string, readonly string[]> = {
  pune: [
    'Shivajinagar',
    'Kothrud',
    'Hinjawadi',
    'Viman Nagar',
    'Baner',
    'Wakad',
    'Aundh',
    'Hadapsar',
    'Magarpatta City',
    'Kharadi',
    'Camp / MG Road',
    'Deccan Gymkhana',
    'Kalyani Nagar',
    'Koregaon Park',
    'Bavdhan',
    'Pashan',
    'Warje',
    'Sinhagad Road',
    'Swargate',
    'Katraj',
    'Bibwewadi',
    'Kondhwa',
    'Pimpri',
    'Chinchwad',
    'Nigdi',
    'Bhosari',
    'Yerawada',
    'Dhanori',
    'Vishrantwadi',
    'Model Colony',
    'Senapati Bapat Road',
  ],
  mumbai: [
    'Bandra West',
    'Bandra East',
    'Bandra Kurla Complex (BKC)',
    'Andheri West',
    'Andheri East',
    'Juhu',
    'Fort',
    'Nariman Point',
    'Colaba',
    'Marine Lines',
    'Churchgate',
    'Dadar West',
    'Dadar East',
    'Lower Parel',
    'Worli',
    'Prabhadevi',
    'Goregaon West',
    'Goregaon East',
    'Malad West',
    'Malad East',
    'Kandivali',
    'Borivali',
    'Powai',
    'Ghatkopar',
    'Kurla',
    'Chembur',
    'Mulund',
    'Thane West',
    'Vashi',
    'Nerul',
    'Belapur',
  ],
  bengaluru: [
    'MG Road',
    'Indiranagar',
    'Koramangala',
    'Whitefield',
    'Electronic City',
    'HSR Layout',
    'BTM Layout',
    'Jayanagar',
    'JP Nagar',
    'Marathahalli',
    'Bellandur',
    'Hebbal',
    'Yelahanka',
    'Malleshwaram',
    'Rajajinagar',
    'Banashankari',
    'Kalyan Nagar',
    'Bannerghatta Road',
    'Richmond Town',
    'Frazer Town',
    'Sarjapur Road',
  ],
  bangalore: [
    'MG Road',
    'Indiranagar',
    'Koramangala',
    'Whitefield',
    'Electronic City',
    'HSR Layout',
    'BTM Layout',
    'Jayanagar',
    'JP Nagar',
    'Marathahalli',
    'Bellandur',
    'Hebbal',
    'Yelahanka',
    'Malleshwaram',
    'Rajajinagar',
    'Banashankari',
    'Kalyan Nagar',
    'Bannerghatta Road',
  ],
  hyderabad: [
    'Madhapur',
    'Hitec City',
    'Gachibowli',
    'Kondapur',
    'Banjara Hills',
    'Jubilee Hills',
    'Kukatpally',
    'Ameerpet',
    'Begumpet',
    'Secunderabad',
    'Abids',
    'Koti',
    'Dilsukhnagar',
    'LB Nagar',
    'Charminar',
    'Miyapur',
    'Manikonda',
    'Uppal',
    'Somajiguda',
    'Panjagutta',
    'Tolichowki',
  ],
  newdelhi: [
    'Connaught Place',
    'Hauz Khas',
    'Saket',
    'Vasant Kunj',
    'South Extension',
    'Lajpat Nagar',
    'Karol Bagh',
    'Chandni Chowk',
    'Dwarka',
    'Rohini',
    'Janakpuri',
    'Pitampura',
    'Mayur Vihar',
    'Laxmi Nagar',
    'Defence Colony',
    'Greater Kailash',
    'Nehru Place',
    'Chanakyapuri',
    'Green Park',
    'Vasant Vihar',
  ],
  delhi: [
    'Connaught Place',
    'Hauz Khas',
    'Saket',
    'Vasant Kunj',
    'South Extension',
    'Lajpat Nagar',
    'Karol Bagh',
    'Chandni Chowk',
    'Dwarka',
    'Rohini',
    'Janakpuri',
    'Pitampura',
    'Mayur Vihar',
    'Laxmi Nagar',
    'Defence Colony',
    'Greater Kailash',
    'Nehru Place',
    'Green Park',
  ],
  chennai: [
    'T. Nagar',
    'Anna Nagar',
    'Adyar',
    'Velachery',
    'Mylapore',
    'Alwarpet',
    'Nungambakkam',
    'Guindy',
    'OMR / Perungudi',
    'Sholinganallur',
    'Thiruvanmiyur',
    'Kilpauk',
    'Egmore',
    'George Town / Parrys',
    'Tambaram',
    'Chromepet',
    'Porur',
    'Besant Nagar',
    'Kotturpuram',
  ],
  kolkata: [
    'Park Street',
    'Salt Lake (Bidhannagar)',
    'New Town',
    'Ballygunge',
    'Alipore',
    'BBD Bagh',
    'Gariahat',
    'Behala',
    'Dum Dum',
    'Howrah',
    'Jadavpur',
    'Shyambazar',
    'Rajarhat',
    'Tollygunge',
    'Esplanade',
    'Lake Town',
    'Bhawanipur',
  ],
  ahmedabad: [
    'Navrangpura',
    'SG Highway',
    'Prahlad Nagar',
    'Bodakdev',
    'Satellite',
    'Vastrapur',
    'Maninagar',
    'Paldi',
    'Ashram Road',
    'Chandkheda',
    'Bopal',
    'Thaltej',
    'Ellis Bridge',
    'Gota',
    'Sindhu Bhavan Road',
  ],
  jaipur: [
    'C-Scheme',
    'Malviya Nagar',
    'Vaishali Nagar',
    'Mansarovar',
    'Raja Park',
    'Tonk Road',
    'MI Road',
    'Bani Park',
    'Jagatpura',
    'Ajmer Road',
    'Pink City / Johari Bazar',
    'Civil Lines',
  ],
  portblair: [
    'Aberdeen Bazaar',
    'Dollygunj',
    'Haddo',
    'Junglighat',
    'Shadipur',
    'Garacharma',
    'Prothrapur',
    'Bathubasthi',
    'Sippighat',
    'Chouldhari',
    'Delanipur',
    'South Point',
  ],
  vijayawada: [
    'Governorpet',
    'Benz Circle',
    'Moghalrajpuram',
    'Suryaraopet',
    'Patamata',
    'Auto Nagar',
    'Bhavanipuram',
    'One Town',
    'Gunadala',
    'Satyanarayanapuram',
  ],
  nalgonda: [
    'Clock Tower',
    'Chityal',
    'Ramagiri',
    'Devarakonda Road',
    'Miryalaguda Road',
    'Prakasham Bazaar',
    'Subhash Nagar',
    'V.T. Colony',
  ],
  gurugram: [
    'DLF Cyber City',
    'Sector 29',
    'Golf Course Road',
    'Golf Course Extension',
    'Sohna Road',
    'MG Road',
    'Sushant Lok',
    'Sector 14',
    'Sector 56',
    'Udyog Vihar',
    'Palam Vihar',
  ],
  noida: [
    'Sector 18',
    'Sector 62',
    'Sector 16 / Film City',
    'Sector 15',
    'Sector 50',
    'Sector 137',
    'Sector 76',
    'Sector 128',
    'Greater Noida West',
  ],
  lucknow: [
    'Hazratganj',
    'Gomti Nagar',
    'Alambagh',
    'Indira Nagar',
    'Mahanagar',
    'Aminabad',
    'Chowk',
    'Ashiyana',
    'Jankipuram',
    'Vibhuti Khand',
  ],
  chandigarh: [
    'Sector 17',
    'Sector 22',
    'Sector 35',
    'Sector 43',
    'Sector 8',
    'Sector 9',
    'Manimajra',
    'Industrial Area Phase 1',
    'Industrial Area Phase 2',
  ],
}

/**
 * Normalizes a city name for lookup.
 * Pure functional: no loops.
 */
export const normalizeCityKey = (cityName: string): string => {
  return cityName
    .toLowerCase()
    .replace(/[^a-z]/g, '')
    .replace(/city$/, '')
    .replace(/urban$/, '')
    .replace(/rural$/, '')
}

/**
 * Returns all localities covering a given city, merged with any live postal branch suggestions.
 * Rule 2: Pure functional composition using Array methods (no loops).
 */
export const getLocalitiesForCity = (
  cityName: string,
  postalBranches: string[] = []
): string[] => {
  const normalizedKey = normalizeCityKey(cityName)
  const masterLocalities = CITY_LOCALITIES_MAP[normalizedKey] || []

  // Clean and normalize postal branches
  const cleanedBranches = postalBranches
    .map((branch) => branch.replace(/\s+(S\.O|B\.O|H\.O|G\.P\.O|Branch Office|Sub Office)$/i, '').trim())
    .filter(Boolean)

  // Merge master list with postal branches and eliminate duplicates using Set
  const combined = Array.from(new Set([...masterLocalities, ...cleanedBranches]))

  if (combined.length === 0) {
    return cleanedBranches.length > 0 ? cleanedBranches : []
  }

  // Sort alphabetically
  return combined.slice().sort((a, b) => a.localeCompare(b))
}
