import type { CanonicalIndianState } from './offlinePincodeMaster'

export interface PostalCircleRegion {
  state: CanonicalIndianState
  defaultCity: string
  defaultDistrict: string
}

export const POSTAL_CIRCLE_PREFIX_MAP: Record<string, PostalCircleRegion> = {
  '11': { state: 'Delhi', defaultCity: 'New Delhi', defaultDistrict: 'Central Delhi' },
  '12': { state: 'Haryana', defaultCity: 'Gurugram', defaultDistrict: 'Gurugram' },
  '13': { state: 'Haryana', defaultCity: 'Ambala', defaultDistrict: 'Ambala' },
  '14': { state: 'Punjab', defaultCity: 'Ludhiana', defaultDistrict: 'Ludhiana' },
  '15': { state: 'Punjab', defaultCity: 'Bathinda', defaultDistrict: 'Bathinda' },
  '16': { state: 'Chandigarh', defaultCity: 'Chandigarh', defaultDistrict: 'Chandigarh' },
  '17': { state: 'Himachal Pradesh', defaultCity: 'Shimla', defaultDistrict: 'Shimla' },
  '18': { state: 'Jammu and Kashmir', defaultCity: 'Jammu', defaultDistrict: 'Jammu' },
  '19': { state: 'Jammu and Kashmir', defaultCity: 'Srinagar', defaultDistrict: 'Srinagar' },
  '20': { state: 'Uttar Pradesh', defaultCity: 'Noida', defaultDistrict: 'Gautam Buddha Nagar' },
  '21': { state: 'Uttar Pradesh', defaultCity: 'Prayagraj', defaultDistrict: 'Prayagraj' },
  '22': { state: 'Uttar Pradesh', defaultCity: 'Lucknow', defaultDistrict: 'Lucknow' },
  '23': { state: 'Uttar Pradesh', defaultCity: 'Mirzapur', defaultDistrict: 'Mirzapur' },
  '24': { state: 'Uttarakhand', defaultCity: 'Dehradun', defaultDistrict: 'Dehradun' },
  '25': { state: 'Uttar Pradesh', defaultCity: 'Meerut', defaultDistrict: 'Meerut' },
  '26': { state: 'Uttarakhand', defaultCity: 'Haldwani', defaultDistrict: 'Nainital' },
  '27': { state: 'Uttar Pradesh', defaultCity: 'Gorakhpur', defaultDistrict: 'Gorakhpur' },
  '28': { state: 'Uttar Pradesh', defaultCity: 'Agra', defaultDistrict: 'Agra' },
  '30': { state: 'Rajasthan', defaultCity: 'Jaipur', defaultDistrict: 'Jaipur' },
  '31': { state: 'Rajasthan', defaultCity: 'Udaipur', defaultDistrict: 'Udaipur' },
  '32': { state: 'Rajasthan', defaultCity: 'Kota', defaultDistrict: 'Kota' },
  '33': { state: 'Rajasthan', defaultCity: 'Bikaner', defaultDistrict: 'Bikaner' },
  '34': { state: 'Rajasthan', defaultCity: 'Jodhpur', defaultDistrict: 'Jodhpur' },
  '36': { state: 'Gujarat', defaultCity: 'Rajkot', defaultDistrict: 'Rajkot' },
  '37': { state: 'Gujarat', defaultCity: 'Jamnagar', defaultDistrict: 'Jamnagar' },
  '38': { state: 'Gujarat', defaultCity: 'Ahmedabad', defaultDistrict: 'Ahmedabad' },
  '39': { state: 'Gujarat', defaultCity: 'Surat', defaultDistrict: 'Surat' },
  '40': { state: 'Maharashtra', defaultCity: 'Mumbai', defaultDistrict: 'Mumbai' },
  '41': { state: 'Maharashtra', defaultCity: 'Pune', defaultDistrict: 'Pune' },
  '42': { state: 'Maharashtra', defaultCity: 'Nashik', defaultDistrict: 'Nashik' },
  '43': { state: 'Maharashtra', defaultCity: 'Chhatrapati Sambhajinagar', defaultDistrict: 'Chhatrapati Sambhajinagar' },
  '44': { state: 'Maharashtra', defaultCity: 'Nagpur', defaultDistrict: 'Nagpur' },
  '45': { state: 'Madhya Pradesh', defaultCity: 'Indore', defaultDistrict: 'Indore' },
  '46': { state: 'Madhya Pradesh', defaultCity: 'Bhopal', defaultDistrict: 'Bhopal' },
  '47': { state: 'Madhya Pradesh', defaultCity: 'Gwalior', defaultDistrict: 'Gwalior' },
  '48': { state: 'Madhya Pradesh', defaultCity: 'Jabalpur', defaultDistrict: 'Jabalpur' },
  '49': { state: 'Chhattisgarh', defaultCity: 'Raipur', defaultDistrict: 'Raipur' },
  '50': { state: 'Telangana', defaultCity: 'Hyderabad', defaultDistrict: 'Hyderabad' },
  '51': { state: 'Andhra Pradesh', defaultCity: 'Tirupati', defaultDistrict: 'Tirupati' },
  '52': { state: 'Andhra Pradesh', defaultCity: 'Vijayawada', defaultDistrict: 'Krishna' },
  '53': { state: 'Andhra Pradesh', defaultCity: 'Visakhapatnam', defaultDistrict: 'Visakhapatnam' },
  '56': { state: 'Karnataka', defaultCity: 'Bengaluru', defaultDistrict: 'Bengaluru Urban' },
  '57': { state: 'Karnataka', defaultCity: 'Mangaluru', defaultDistrict: 'Dakshina Kannada' },
  '58': { state: 'Karnataka', defaultCity: 'Hubballi', defaultDistrict: 'Dharwad' },
  '59': { state: 'Karnataka', defaultCity: 'Belagavi', defaultDistrict: 'Belagavi' },
  '60': { state: 'Tamil Nadu', defaultCity: 'Chennai', defaultDistrict: 'Chennai' },
  '61': { state: 'Tamil Nadu', defaultCity: 'Thanjavur', defaultDistrict: 'Thanjavur' },
  '62': { state: 'Tamil Nadu', defaultCity: 'Madurai', defaultDistrict: 'Madurai' },
  '63': { state: 'Tamil Nadu', defaultCity: 'Coimbatore', defaultDistrict: 'Coimbatore' },
  '64': { state: 'Tamil Nadu', defaultCity: 'Coimbatore', defaultDistrict: 'Coimbatore' },
  '67': { state: 'Kerala', defaultCity: 'Kozhikode', defaultDistrict: 'Kozhikode' },
  '68': { state: 'Kerala', defaultCity: 'Kochi', defaultDistrict: 'Ernakulam' },
  '69': { state: 'Kerala', defaultCity: 'Thiruvananthapuram', defaultDistrict: 'Thiruvananthapuram' },
  '70': { state: 'West Bengal', defaultCity: 'Kolkata', defaultDistrict: 'Kolkata' },
  '71': { state: 'West Bengal', defaultCity: 'Howrah', defaultDistrict: 'Howrah' },
  '72': { state: 'West Bengal', defaultCity: 'Kharagpur', defaultDistrict: 'Paschim Medinipur' },
  '73': { state: 'West Bengal', defaultCity: 'Siliguri', defaultDistrict: 'Darjeeling' },
  '74': { state: 'Andaman and Nicobar Islands', defaultCity: 'Port Blair', defaultDistrict: 'South Andaman' },
  '75': { state: 'Odisha', defaultCity: 'Bhubaneswar', defaultDistrict: 'Khordha' },
  '76': { state: 'Odisha', defaultCity: 'Cuttack', defaultDistrict: 'Cuttack' },
  '77': { state: 'Odisha', defaultCity: 'Sambalpur', defaultDistrict: 'Sambalpur' },
  '78': { state: 'Assam', defaultCity: 'Guwahati', defaultDistrict: 'Kamrup Metropolitan' },
  '79': { state: 'Meghalaya', defaultCity: 'Shillong', defaultDistrict: 'East Khasi Hills' },
  '80': { state: 'Bihar', defaultCity: 'Patna', defaultDistrict: 'Patna' },
  '81': { state: 'Bihar', defaultCity: 'Bhagalpur', defaultDistrict: 'Bhagalpur' },
  '82': { state: 'Bihar', defaultCity: 'Gaya', defaultDistrict: 'Gaya' },
  '83': { state: 'Jharkhand', defaultCity: 'Ranchi', defaultDistrict: 'Ranchi' },
  '84': { state: 'Bihar', defaultCity: 'Muzaffarpur', defaultDistrict: 'Muzaffarpur' },
  '85': { state: 'Bihar', defaultCity: 'Darbhanga', defaultDistrict: 'Darbhanga' },
}
