import type { CanonicalIndianState } from './offlinePincodeMaster'

export interface PostalCircleRegion {
  state: CanonicalIndianState
  defaultCity: string
  defaultDistrict: string
}

/**
 * High-priority exact 6-digit or pattern matches for unique Union Territory enclaves
 * and island territories that share 2/3 digit prefixes with neighboring states.
 */
export const SPECIAL_UT_PINCODE_MAP: Record<string, PostalCircleRegion> = {
  // Dadra and Nagar Haveli and Daman and Diu
  '396210': { state: 'Dadra and Nagar Haveli and Daman and Diu', defaultCity: 'Daman', defaultDistrict: 'Daman' },
  '396215': { state: 'Dadra and Nagar Haveli and Daman and Diu', defaultCity: 'Daman', defaultDistrict: 'Daman' },
  '396220': { state: 'Dadra and Nagar Haveli and Daman and Diu', defaultCity: 'Daman', defaultDistrict: 'Daman' },
  '396230': { state: 'Dadra and Nagar Haveli and Daman and Diu', defaultCity: 'Silvassa', defaultDistrict: 'Dadra and Nagar Haveli' },
  '396235': { state: 'Dadra and Nagar Haveli and Daman and Diu', defaultCity: 'Silvassa', defaultDistrict: 'Dadra and Nagar Haveli' },
  '396240': { state: 'Dadra and Nagar Haveli and Daman and Diu', defaultCity: 'Silvassa', defaultDistrict: 'Dadra and Nagar Haveli' },
  '362520': { state: 'Dadra and Nagar Haveli and Daman and Diu', defaultCity: 'Diu', defaultDistrict: 'Diu' },

  // Puducherry Enclaves
  '673310': { state: 'Puducherry', defaultCity: 'Mahe', defaultDistrict: 'Mahe' },
  '533464': { state: 'Puducherry', defaultCity: 'Yanam', defaultDistrict: 'Yanam' },
  '609609': { state: 'Puducherry', defaultCity: 'Karaikal', defaultDistrict: 'Karaikal' },
  '609602': { state: 'Puducherry', defaultCity: 'Karaikal', defaultDistrict: 'Karaikal' },

  // Lakshadweep Islands (682551 - 682559)
  '682551': { state: 'Lakshadweep', defaultCity: 'Amini', defaultDistrict: 'Lakshadweep' },
  '682552': { state: 'Lakshadweep', defaultCity: 'Andrott', defaultDistrict: 'Lakshadweep' },
  '682553': { state: 'Lakshadweep', defaultCity: 'Agatti', defaultDistrict: 'Lakshadweep' },
  '682554': { state: 'Lakshadweep', defaultCity: 'Kalpeni', defaultDistrict: 'Lakshadweep' },
  '682555': { state: 'Lakshadweep', defaultCity: 'Kavaratti', defaultDistrict: 'Lakshadweep' },
  '682556': { state: 'Lakshadweep', defaultCity: 'Minicoy', defaultDistrict: 'Lakshadweep' },
  '682557': { state: 'Lakshadweep', defaultCity: 'Kadmat', defaultDistrict: 'Lakshadweep' },
  '682558': { state: 'Lakshadweep', defaultCity: 'Kiltan', defaultDistrict: 'Lakshadweep' },
  '682559': { state: 'Lakshadweep', defaultCity: 'Chetlat', defaultDistrict: 'Lakshadweep' },
}

/**
 * 3-Digit Prefix Map for precision resolution of all Indian Districts,
 * Union Territories, Metros, and Tier-1/2/3 Cities covering every corner of India.
 */
export const SUB_REGION_3DIGIT_PREFIX_MAP: Record<string, PostalCircleRegion> = {
  // --- ZONE 1: Delhi, Haryana, Punjab, Himachal, J&K, Ladakh, Chandigarh ---
  '110': { state: 'Delhi', defaultCity: 'New Delhi', defaultDistrict: 'Central Delhi' },
  '121': { state: 'Haryana', defaultCity: 'Faridabad', defaultDistrict: 'Faridabad' },
  '122': { state: 'Haryana', defaultCity: 'Gurugram', defaultDistrict: 'Gurugram' },
  '123': { state: 'Haryana', defaultCity: 'Rewari', defaultDistrict: 'Rewari' },
  '124': { state: 'Haryana', defaultCity: 'Rohtak', defaultDistrict: 'Rohtak' },
  '125': { state: 'Haryana', defaultCity: 'Hisar', defaultDistrict: 'Hisar' },
  '126': { state: 'Haryana', defaultCity: 'Jind', defaultDistrict: 'Jind' },
  '127': { state: 'Haryana', defaultCity: 'Bhiwani', defaultDistrict: 'Bhiwani' },
  '128': { state: 'Haryana', defaultCity: 'Charkhi Dadri', defaultDistrict: 'Charkhi Dadri' },
  '131': { state: 'Haryana', defaultCity: 'Sonipat', defaultDistrict: 'Sonipat' },
  '132': { state: 'Haryana', defaultCity: 'Panipat', defaultDistrict: 'Panipat' },
  '133': { state: 'Haryana', defaultCity: 'Ambala', defaultDistrict: 'Ambala' },
  '134': { state: 'Haryana', defaultCity: 'Panchkula', defaultDistrict: 'Panchkula' },
  '135': { state: 'Haryana', defaultCity: 'Yamunanagar', defaultDistrict: 'Yamunanagar' },
  '136': { state: 'Haryana', defaultCity: 'Kurukshetra', defaultDistrict: 'Kurukshetra' },
  '140': { state: 'Punjab', defaultCity: 'Mohali', defaultDistrict: 'Mohali' },
  '141': { state: 'Punjab', defaultCity: 'Ludhiana', defaultDistrict: 'Ludhiana' },
  '142': { state: 'Punjab', defaultCity: 'Moga', defaultDistrict: 'Moga' },
  '143': { state: 'Punjab', defaultCity: 'Amritsar', defaultDistrict: 'Amritsar' },
  '144': { state: 'Punjab', defaultCity: 'Jalandhar', defaultDistrict: 'Jalandhar' },
  '145': { state: 'Punjab', defaultCity: 'Pathankot', defaultDistrict: 'Pathankot' },
  '146': { state: 'Punjab', defaultCity: 'Hoshiarpur', defaultDistrict: 'Hoshiarpur' },
  '147': { state: 'Punjab', defaultCity: 'Patiala', defaultDistrict: 'Patiala' },
  '148': { state: 'Punjab', defaultCity: 'Sangrur', defaultDistrict: 'Sangrur' },
  '151': { state: 'Punjab', defaultCity: 'Bathinda', defaultDistrict: 'Bathinda' },
  '152': { state: 'Punjab', defaultCity: 'Firozpur', defaultDistrict: 'Firozpur' },
  '160': { state: 'Chandigarh', defaultCity: 'Chandigarh', defaultDistrict: 'Chandigarh' },
  '171': { state: 'Himachal Pradesh', defaultCity: 'Shimla', defaultDistrict: 'Shimla' },
  '172': { state: 'Himachal Pradesh', defaultCity: 'Reckong Peo', defaultDistrict: 'Kinnaur' },
  '173': { state: 'Himachal Pradesh', defaultCity: 'Solan', defaultDistrict: 'Solan' },
  '174': { state: 'Himachal Pradesh', defaultCity: 'Bilaspur', defaultDistrict: 'Bilaspur' },
  '175': { state: 'Himachal Pradesh', defaultCity: 'Mandi', defaultDistrict: 'Mandi' },
  '176': { state: 'Himachal Pradesh', defaultCity: 'Dharamshala', defaultDistrict: 'Kangra' },
  '177': { state: 'Himachal Pradesh', defaultCity: 'Hamirpur', defaultDistrict: 'Hamirpur' },
  '180': { state: 'Jammu and Kashmir', defaultCity: 'Jammu', defaultDistrict: 'Jammu' },
  '181': { state: 'Jammu and Kashmir', defaultCity: 'Samba', defaultDistrict: 'Samba' },
  '182': { state: 'Jammu and Kashmir', defaultCity: 'Udhampur', defaultDistrict: 'Udhampur' },
  '184': { state: 'Jammu and Kashmir', defaultCity: 'Kathua', defaultDistrict: 'Kathua' },
  '185': { state: 'Jammu and Kashmir', defaultCity: 'Rajouri', defaultDistrict: 'Rajouri' },
  '190': { state: 'Jammu and Kashmir', defaultCity: 'Srinagar', defaultDistrict: 'Srinagar' },
  '191': { state: 'Jammu and Kashmir', defaultCity: 'Ganderbal', defaultDistrict: 'Ganderbal' },
  '192': { state: 'Jammu and Kashmir', defaultCity: 'Anantnag', defaultDistrict: 'Anantnag' },
  '193': { state: 'Jammu and Kashmir', defaultCity: 'Baramulla', defaultDistrict: 'Baramulla' },
  '194': { state: 'Ladakh', defaultCity: 'Leh', defaultDistrict: 'Leh' },

  // --- ZONE 2: Uttar Pradesh & Uttarakhand ---
  '201': { state: 'Uttar Pradesh', defaultCity: 'Noida', defaultDistrict: 'Gautam Buddha Nagar' },
  '202': { state: 'Uttar Pradesh', defaultCity: 'Aligarh', defaultDistrict: 'Aligarh' },
  '203': { state: 'Uttar Pradesh', defaultCity: 'Bulandshahr', defaultDistrict: 'Bulandshahr' },
  '204': { state: 'Uttar Pradesh', defaultCity: 'Hathras', defaultDistrict: 'Hathras' },
  '205': { state: 'Uttar Pradesh', defaultCity: 'Mainpuri', defaultDistrict: 'Mainpuri' },
  '206': { state: 'Uttar Pradesh', defaultCity: 'Etawah', defaultDistrict: 'Etawah' },
  '207': { state: 'Uttar Pradesh', defaultCity: 'Etah', defaultDistrict: 'Etah' },
  '208': { state: 'Uttar Pradesh', defaultCity: 'Kanpur', defaultDistrict: 'Kanpur Nagar' },
  '209': { state: 'Uttar Pradesh', defaultCity: 'Akbarpur', defaultDistrict: 'Kanpur Dehat' },
  '210': { state: 'Uttar Pradesh', defaultCity: 'Banda', defaultDistrict: 'Banda' },
  '211': { state: 'Uttar Pradesh', defaultCity: 'Prayagraj', defaultDistrict: 'Prayagraj' },
  '212': { state: 'Uttar Pradesh', defaultCity: 'Kaushambi', defaultDistrict: 'Kaushambi' },
  '221': { state: 'Uttar Pradesh', defaultCity: 'Varanasi', defaultDistrict: 'Varanasi' },
  '222': { state: 'Uttar Pradesh', defaultCity: 'Jaunpur', defaultDistrict: 'Jaunpur' },
  '223': { state: 'Uttar Pradesh', defaultCity: 'Azamgarh', defaultDistrict: 'Azamgarh' },
  '224': { state: 'Uttar Pradesh', defaultCity: 'Ayodhya', defaultDistrict: 'Ayodhya' },
  '225': { state: 'Uttar Pradesh', defaultCity: 'Barabanki', defaultDistrict: 'Barabanki' },
  '226': { state: 'Uttar Pradesh', defaultCity: 'Lucknow', defaultDistrict: 'Lucknow' },
  '227': { state: 'Uttar Pradesh', defaultCity: 'Amethi', defaultDistrict: 'Amethi' },
  '228': { state: 'Uttar Pradesh', defaultCity: 'Sultanpur', defaultDistrict: 'Sultanpur' },
  '229': { state: 'Uttar Pradesh', defaultCity: 'Rae Bareli', defaultDistrict: 'Rae Bareli' },
  '230': { state: 'Uttar Pradesh', defaultCity: 'Pratapgarh', defaultDistrict: 'Pratapgarh' },
  '231': { state: 'Uttar Pradesh', defaultCity: 'Mirzapur', defaultDistrict: 'Mirzapur' },
  '232': { state: 'Uttar Pradesh', defaultCity: 'Chandauli', defaultDistrict: 'Chandauli' },
  '233': { state: 'Uttar Pradesh', defaultCity: 'Ghazipur', defaultDistrict: 'Ghazipur' },
  '241': { state: 'Uttar Pradesh', defaultCity: 'Hardoi', defaultDistrict: 'Hardoi' },
  '242': { state: 'Uttar Pradesh', defaultCity: 'Shahjahanpur', defaultDistrict: 'Shahjahanpur' },
  '243': { state: 'Uttar Pradesh', defaultCity: 'Bareilly', defaultDistrict: 'Bareilly' },
  '244': { state: 'Uttar Pradesh', defaultCity: 'Moradabad', defaultDistrict: 'Moradabad' },
  '245': { state: 'Uttar Pradesh', defaultCity: 'Hapur', defaultDistrict: 'Hapur' },
  '246': { state: 'Uttarakhand', defaultCity: 'Pauri', defaultDistrict: 'Pauri Garhwal' },
  '247': { state: 'Uttar Pradesh', defaultCity: 'Saharanpur', defaultDistrict: 'Saharanpur' },
  '248': { state: 'Uttarakhand', defaultCity: 'Dehradun', defaultDistrict: 'Dehradun' },
  '249': { state: 'Uttarakhand', defaultCity: 'Haridwar', defaultDistrict: 'Haridwar' },
  '250': { state: 'Uttar Pradesh', defaultCity: 'Meerut', defaultDistrict: 'Meerut' },
  '251': { state: 'Uttar Pradesh', defaultCity: 'Muzaffarnagar', defaultDistrict: 'Muzaffarnagar' },
  '261': { state: 'Uttar Pradesh', defaultCity: 'Sitapur', defaultDistrict: 'Sitapur' },
  '262': { state: 'Uttarakhand', defaultCity: 'Pithoragarh', defaultDistrict: 'Pithoragarh' },
  '263': { state: 'Uttarakhand', defaultCity: 'Nainital', defaultDistrict: 'Nainital' },
  '271': { state: 'Uttar Pradesh', defaultCity: 'Gonda', defaultDistrict: 'Gonda' },
  '272': { state: 'Uttar Pradesh', defaultCity: 'Basti', defaultDistrict: 'Basti' },
  '273': { state: 'Uttar Pradesh', defaultCity: 'Gorakhpur', defaultDistrict: 'Gorakhpur' },
  '274': { state: 'Uttar Pradesh', defaultCity: 'Deoria', defaultDistrict: 'Deoria' },
  '275': { state: 'Uttar Pradesh', defaultCity: 'Mau', defaultDistrict: 'Mau' },
  '276': { state: 'Uttar Pradesh', defaultCity: 'Azamgarh', defaultDistrict: 'Azamgarh' },
  '277': { state: 'Uttar Pradesh', defaultCity: 'Ballia', defaultDistrict: 'Ballia' },
  '281': { state: 'Uttar Pradesh', defaultCity: 'Mathura', defaultDistrict: 'Mathura' },
  '282': { state: 'Uttar Pradesh', defaultCity: 'Agra', defaultDistrict: 'Agra' },
  '283': { state: 'Uttar Pradesh', defaultCity: 'Firozabad', defaultDistrict: 'Firozabad' },
  '284': { state: 'Uttar Pradesh', defaultCity: 'Jhansi', defaultDistrict: 'Jhansi' },
  '285': { state: 'Uttar Pradesh', defaultCity: 'Orai', defaultDistrict: 'Jalaun' },

  // --- ZONE 3: Rajasthan, Gujarat, DNH & DD ---
  '301': { state: 'Rajasthan', defaultCity: 'Alwar', defaultDistrict: 'Alwar' },
  '302': { state: 'Rajasthan', defaultCity: 'Jaipur', defaultDistrict: 'Jaipur' },
  '303': { state: 'Rajasthan', defaultCity: 'Dausa', defaultDistrict: 'Dausa' },
  '304': { state: 'Rajasthan', defaultCity: 'Tonk', defaultDistrict: 'Tonk' },
  '305': { state: 'Rajasthan', defaultCity: 'Ajmer', defaultDistrict: 'Ajmer' },
  '306': { state: 'Rajasthan', defaultCity: 'Pali', defaultDistrict: 'Pali' },
  '307': { state: 'Rajasthan', defaultCity: 'Sirohi', defaultDistrict: 'Sirohi' },
  '311': { state: 'Rajasthan', defaultCity: 'Bhilwara', defaultDistrict: 'Bhilwara' },
  '312': { state: 'Rajasthan', defaultCity: 'Chittorgarh', defaultDistrict: 'Chittorgarh' },
  '313': { state: 'Rajasthan', defaultCity: 'Udaipur', defaultDistrict: 'Udaipur' },
  '314': { state: 'Rajasthan', defaultCity: 'Dungarpur', defaultDistrict: 'Dungarpur' },
  '321': { state: 'Rajasthan', defaultCity: 'Bharatpur', defaultDistrict: 'Bharatpur' },
  '322': { state: 'Rajasthan', defaultCity: 'Sawai Madhopur', defaultDistrict: 'Sawai Madhopur' },
  '323': { state: 'Rajasthan', defaultCity: 'Bundi', defaultDistrict: 'Bundi' },
  '324': { state: 'Rajasthan', defaultCity: 'Kota', defaultDistrict: 'Kota' },
  '325': { state: 'Rajasthan', defaultCity: 'Baran', defaultDistrict: 'Baran' },
  '326': { state: 'Rajasthan', defaultCity: 'Jhalawar', defaultDistrict: 'Jhalawar' },
  '331': { state: 'Rajasthan', defaultCity: 'Churu', defaultDistrict: 'Churu' },
  '332': { state: 'Rajasthan', defaultCity: 'Sikar', defaultDistrict: 'Sikar' },
  '333': { state: 'Rajasthan', defaultCity: 'Jhunjhunu', defaultDistrict: 'Jhunjhunu' },
  '334': { state: 'Rajasthan', defaultCity: 'Bikaner', defaultDistrict: 'Bikaner' },
  '335': { state: 'Rajasthan', defaultCity: 'Sri Ganganagar', defaultDistrict: 'Sri Ganganagar' },
  '341': { state: 'Rajasthan', defaultCity: 'Nagaur', defaultDistrict: 'Nagaur' },
  '342': { state: 'Rajasthan', defaultCity: 'Jodhpur', defaultDistrict: 'Jodhpur' },
  '343': { state: 'Rajasthan', defaultCity: 'Jalore', defaultDistrict: 'Jalore' },
  '344': { state: 'Rajasthan', defaultCity: 'Barmer', defaultDistrict: 'Barmer' },
  '345': { state: 'Rajasthan', defaultCity: 'Jaisalmer', defaultDistrict: 'Jaisalmer' },
  '360': { state: 'Gujarat', defaultCity: 'Rajkot', defaultDistrict: 'Rajkot' },
  '361': { state: 'Gujarat', defaultCity: 'Jamnagar', defaultDistrict: 'Jamnagar' },
  '362': { state: 'Gujarat', defaultCity: 'Junagadh', defaultDistrict: 'Junagadh' },
  '363': { state: 'Gujarat', defaultCity: 'Surendranagar', defaultDistrict: 'Surendranagar' },
  '364': { state: 'Gujarat', defaultCity: 'Bhavnagar', defaultDistrict: 'Bhavnagar' },
  '365': { state: 'Gujarat', defaultCity: 'Amreli', defaultDistrict: 'Amreli' },
  '370': { state: 'Gujarat', defaultCity: 'Bhuj', defaultDistrict: 'Kutch' },
  '380': { state: 'Gujarat', defaultCity: 'Ahmedabad', defaultDistrict: 'Ahmedabad' },
  '382': { state: 'Gujarat', defaultCity: 'Gandhinagar', defaultDistrict: 'Gandhinagar' },
  '383': { state: 'Gujarat', defaultCity: 'Himatnagar', defaultDistrict: 'Sabarkantha' },
  '384': { state: 'Gujarat', defaultCity: 'Mehsana', defaultDistrict: 'Mehsana' },
  '385': { state: 'Gujarat', defaultCity: 'Palanpur', defaultDistrict: 'Banaskantha' },
  '387': { state: 'Gujarat', defaultCity: 'Nadiad', defaultDistrict: 'Kheda' },
  '388': { state: 'Gujarat', defaultCity: 'Anand', defaultDistrict: 'Anand' },
  '389': { state: 'Gujarat', defaultCity: 'Godhra', defaultDistrict: 'Panchmahal' },
  '390': { state: 'Gujarat', defaultCity: 'Vadodara', defaultDistrict: 'Vadodara' },
  '391': { state: 'Gujarat', defaultCity: 'Vadodara Rural', defaultDistrict: 'Vadodara' },
  '392': { state: 'Gujarat', defaultCity: 'Bharuch', defaultDistrict: 'Bharuch' },
  '393': { state: 'Gujarat', defaultCity: 'Ankleshwar', defaultDistrict: 'Bharuch' },
  '394': { state: 'Gujarat', defaultCity: 'Surat Rural', defaultDistrict: 'Surat' },
  '395': { state: 'Gujarat', defaultCity: 'Surat', defaultDistrict: 'Surat' },
  '396': { state: 'Gujarat', defaultCity: 'Valsad', defaultDistrict: 'Valsad' },

  // --- ZONE 4: Maharashtra, Goa, Madhya Pradesh, Chhattisgarh ---
  '400': { state: 'Maharashtra', defaultCity: 'Mumbai', defaultDistrict: 'Mumbai' },
  '401': { state: 'Maharashtra', defaultCity: 'Thane', defaultDistrict: 'Thane' },
  '402': { state: 'Maharashtra', defaultCity: 'Alibag', defaultDistrict: 'Raigad' },
  '403': { state: 'Goa', defaultCity: 'Panaji', defaultDistrict: 'North Goa' },
  '410': { state: 'Maharashtra', defaultCity: 'Lonavala', defaultDistrict: 'Pune' },
  '411': { state: 'Maharashtra', defaultCity: 'Pune', defaultDistrict: 'Pune' },
  '412': { state: 'Maharashtra', defaultCity: 'Baramati', defaultDistrict: 'Pune' },
  '413': { state: 'Maharashtra', defaultCity: 'Solapur', defaultDistrict: 'Solapur' },
  '414': { state: 'Maharashtra', defaultCity: 'Ahmednagar', defaultDistrict: 'Ahmednagar' },
  '415': { state: 'Maharashtra', defaultCity: 'Satara', defaultDistrict: 'Satara' },
  '416': { state: 'Maharashtra', defaultCity: 'Kolhapur', defaultDistrict: 'Kolhapur' },
  '421': { state: 'Maharashtra', defaultCity: 'Kalyan', defaultDistrict: 'Thane' },
  '422': { state: 'Maharashtra', defaultCity: 'Nashik', defaultDistrict: 'Nashik' },
  '423': { state: 'Maharashtra', defaultCity: 'Malegaon', defaultDistrict: 'Nashik' },
  '424': { state: 'Maharashtra', defaultCity: 'Dhule', defaultDistrict: 'Dhule' },
  '425': { state: 'Maharashtra', defaultCity: 'Jalgaon', defaultDistrict: 'Jalgaon' },
  '431': { state: 'Maharashtra', defaultCity: 'Chhatrapati Sambhajinagar', defaultDistrict: 'Chhatrapati Sambhajinagar' },
  '440': { state: 'Maharashtra', defaultCity: 'Nagpur', defaultDistrict: 'Nagpur' },
  '441': { state: 'Maharashtra', defaultCity: 'Bhandara', defaultDistrict: 'Bhandara' },
  '442': { state: 'Maharashtra', defaultCity: 'Wardha', defaultDistrict: 'Wardha' },
  '443': { state: 'Maharashtra', defaultCity: 'Buldhana', defaultDistrict: 'Buldhana' },
  '444': { state: 'Maharashtra', defaultCity: 'Amravati', defaultDistrict: 'Amravati' },
  '445': { state: 'Maharashtra', defaultCity: 'Yavatmal', defaultDistrict: 'Yavatmal' },
  '450': { state: 'Madhya Pradesh', defaultCity: 'Khandwa', defaultDistrict: 'Khandwa' },
  '451': { state: 'Madhya Pradesh', defaultCity: 'Khargone', defaultDistrict: 'Khargone' },
  '452': { state: 'Madhya Pradesh', defaultCity: 'Indore', defaultDistrict: 'Indore' },
  '453': { state: 'Madhya Pradesh', defaultCity: 'Mhow', defaultDistrict: 'Indore' },
  '454': { state: 'Madhya Pradesh', defaultCity: 'Dhar', defaultDistrict: 'Dhar' },
  '455': { state: 'Madhya Pradesh', defaultCity: 'Dewas', defaultDistrict: 'Dewas' },
  '456': { state: 'Madhya Pradesh', defaultCity: 'Ujjain', defaultDistrict: 'Ujjain' },
  '457': { state: 'Madhya Pradesh', defaultCity: 'Ratlam', defaultDistrict: 'Ratlam' },
  '458': { state: 'Madhya Pradesh', defaultCity: 'Mandsaur', defaultDistrict: 'Mandsaur' },
  '460': { state: 'Madhya Pradesh', defaultCity: 'Betul', defaultDistrict: 'Betul' },
  '461': { state: 'Madhya Pradesh', defaultCity: 'Narmadapuram', defaultDistrict: 'Narmadapuram' },
  '462': { state: 'Madhya Pradesh', defaultCity: 'Bhopal', defaultDistrict: 'Bhopal' },
  '464': { state: 'Madhya Pradesh', defaultCity: 'Vidisha', defaultDistrict: 'Vidisha' },
  '465': { state: 'Madhya Pradesh', defaultCity: 'Shajapur', defaultDistrict: 'Shajapur' },
  '466': { state: 'Madhya Pradesh', defaultCity: 'Sehore', defaultDistrict: 'Sehore' },
  '470': { state: 'Madhya Pradesh', defaultCity: 'Sagar', defaultDistrict: 'Sagar' },
  '471': { state: 'Madhya Pradesh', defaultCity: 'Chhatarpur', defaultDistrict: 'Chhatarpur' },
  '472': { state: 'Madhya Pradesh', defaultCity: 'Tikamgarh', defaultDistrict: 'Tikamgarh' },
  '473': { state: 'Madhya Pradesh', defaultCity: 'Guna', defaultDistrict: 'Guna' },
  '474': { state: 'Madhya Pradesh', defaultCity: 'Gwalior', defaultDistrict: 'Gwalior' },
  '475': { state: 'Madhya Pradesh', defaultCity: 'Datia', defaultDistrict: 'Datia' },
  '476': { state: 'Madhya Pradesh', defaultCity: 'Morena', defaultDistrict: 'Morena' },
  '477': { state: 'Madhya Pradesh', defaultCity: 'Bhind', defaultDistrict: 'Bhind' },
  '480': { state: 'Madhya Pradesh', defaultCity: 'Chhindwara', defaultDistrict: 'Chhindwara' },
  '481': { state: 'Madhya Pradesh', defaultCity: 'Balaghat', defaultDistrict: 'Balaghat' },
  '482': { state: 'Madhya Pradesh', defaultCity: 'Jabalpur', defaultDistrict: 'Jabalpur' },
  '483': { state: 'Madhya Pradesh', defaultCity: 'Katni', defaultDistrict: 'Katni' },
  '484': { state: 'Madhya Pradesh', defaultCity: 'Shahdol', defaultDistrict: 'Shahdol' },
  '485': { state: 'Madhya Pradesh', defaultCity: 'Satna', defaultDistrict: 'Satna' },
  '486': { state: 'Madhya Pradesh', defaultCity: 'Rewa', defaultDistrict: 'Rewa' },
  '490': { state: 'Chhattisgarh', defaultCity: 'Bhilai', defaultDistrict: 'Durg' },
  '491': { state: 'Chhattisgarh', defaultCity: 'Rajnandgaon', defaultDistrict: 'Rajnandgaon' },
  '492': { state: 'Chhattisgarh', defaultCity: 'Raipur', defaultDistrict: 'Raipur' },
  '493': { state: 'Chhattisgarh', defaultCity: 'Mahasamund', defaultDistrict: 'Mahasamund' },
  '494': { state: 'Chhattisgarh', defaultCity: 'Jagdalpur', defaultDistrict: 'Bastar' },
  '495': { state: 'Chhattisgarh', defaultCity: 'Bilaspur', defaultDistrict: 'Bilaspur' },
  '496': { state: 'Chhattisgarh', defaultCity: 'Raigarh', defaultDistrict: 'Raigarh' },
  '497': { state: 'Chhattisgarh', defaultCity: 'Ambikapur', defaultDistrict: 'Surguja' },

  // --- ZONE 5: Telangana, Andhra Pradesh, Karnataka ---
  '500': { state: 'Telangana', defaultCity: 'Hyderabad', defaultDistrict: 'Hyderabad' },
  '501': { state: 'Telangana', defaultCity: 'Ranga Reddy', defaultDistrict: 'Ranga Reddy' },
  '502': { state: 'Telangana', defaultCity: 'Sangareddy', defaultDistrict: 'Sangareddy' },
  '503': { state: 'Telangana', defaultCity: 'Nizamabad', defaultDistrict: 'Nizamabad' },
  '504': { state: 'Telangana', defaultCity: 'Adilabad', defaultDistrict: 'Adilabad' },
  '505': { state: 'Telangana', defaultCity: 'Karimnagar', defaultDistrict: 'Karimnagar' },
  '506': { state: 'Telangana', defaultCity: 'Warangal', defaultDistrict: 'Warangal' },
  '507': { state: 'Telangana', defaultCity: 'Khammam', defaultDistrict: 'Khammam' },
  '508': { state: 'Telangana', defaultCity: 'Nalgonda', defaultDistrict: 'Nalgonda' },
  '509': { state: 'Telangana', defaultCity: 'Mahabubnagar', defaultDistrict: 'Mahabubnagar' },
  '515': { state: 'Andhra Pradesh', defaultCity: 'Anantapur', defaultDistrict: 'Anantapur' },
  '516': { state: 'Andhra Pradesh', defaultCity: 'Kadapa', defaultDistrict: 'YSR Kadapa' },
  '517': { state: 'Andhra Pradesh', defaultCity: 'Tirupati', defaultDistrict: 'Tirupati' },
  '518': { state: 'Andhra Pradesh', defaultCity: 'Kurnool', defaultDistrict: 'Kurnool' },
  '520': { state: 'Andhra Pradesh', defaultCity: 'Vijayawada', defaultDistrict: 'NTR' },
  '521': { state: 'Andhra Pradesh', defaultCity: 'Machilipatnam', defaultDistrict: 'Krishna' },
  '522': { state: 'Andhra Pradesh', defaultCity: 'Guntur', defaultDistrict: 'Guntur' },
  '523': { state: 'Andhra Pradesh', defaultCity: 'Ongole', defaultDistrict: 'Prakasam' },
  '524': { state: 'Andhra Pradesh', defaultCity: 'Nellore', defaultDistrict: 'Nellore' },
  '530': { state: 'Andhra Pradesh', defaultCity: 'Visakhapatnam', defaultDistrict: 'Visakhapatnam' },
  '531': { state: 'Andhra Pradesh', defaultCity: 'Anakapalle', defaultDistrict: 'Anakapalle' },
  '532': { state: 'Andhra Pradesh', defaultCity: 'Srikakulam', defaultDistrict: 'Srikakulam' },
  '533': { state: 'Andhra Pradesh', defaultCity: 'Kakinada', defaultDistrict: 'Kakinada' },
  '534': { state: 'Andhra Pradesh', defaultCity: 'Eluru', defaultDistrict: 'Eluru' },
  '535': { state: 'Andhra Pradesh', defaultCity: 'Vizianagaram', defaultDistrict: 'Vizianagaram' },
  '560': { state: 'Karnataka', defaultCity: 'Bengaluru', defaultDistrict: 'Bengaluru Urban' },
  '561': { state: 'Karnataka', defaultCity: 'Chikkaballapura', defaultDistrict: 'Chikkaballapura' },
  '562': { state: 'Karnataka', defaultCity: 'Ramanagara', defaultDistrict: 'Ramanagara' },
  '563': { state: 'Karnataka', defaultCity: 'Kolar', defaultDistrict: 'Kolar' },
  '570': { state: 'Karnataka', defaultCity: 'Mysuru', defaultDistrict: 'Mysuru' },
  '571': { state: 'Karnataka', defaultCity: 'Chamarajanagar', defaultDistrict: 'Chamarajanagar' },
  '572': { state: 'Karnataka', defaultCity: 'Tumakuru', defaultDistrict: 'Tumakuru' },
  '573': { state: 'Karnataka', defaultCity: 'Hassan', defaultDistrict: 'Hassan' },
  '574': { state: 'Karnataka', defaultCity: 'Puttur', defaultDistrict: 'Dakshina Kannada' },
  '575': { state: 'Karnataka', defaultCity: 'Mangaluru', defaultDistrict: 'Dakshina Kannada' },
  '576': { state: 'Karnataka', defaultCity: 'Udupi', defaultDistrict: 'Udupi' },
  '577': { state: 'Karnataka', defaultCity: 'Shivamogga', defaultDistrict: 'Shivamogga' },
  '580': { state: 'Karnataka', defaultCity: 'Hubballi', defaultDistrict: 'Dharwad' },
  '581': { state: 'Karnataka', defaultCity: 'Karwar', defaultDistrict: 'Uttara Kannada' },
  '582': { state: 'Karnataka', defaultCity: 'Gadag', defaultDistrict: 'Gadag' },
  '583': { state: 'Karnataka', defaultCity: 'Ballari', defaultDistrict: 'Ballari' },
  '584': { state: 'Karnataka', defaultCity: 'Raichur', defaultDistrict: 'Raichur' },
  '585': { state: 'Karnataka', defaultCity: 'Kalaburagi', defaultDistrict: 'Kalaburagi' },
  '586': { state: 'Karnataka', defaultCity: 'Vijayapura', defaultDistrict: 'Vijayapura' },
  '587': { state: 'Karnataka', defaultCity: 'Bagalkote', defaultDistrict: 'Bagalkote' },
  '590': { state: 'Karnataka', defaultCity: 'Belagavi', defaultDistrict: 'Belagavi' },
  '591': { state: 'Karnataka', defaultCity: 'Chikkodi', defaultDistrict: 'Belagavi' },

  // --- ZONE 6: Tamil Nadu, Kerala, Lakshadweep, Puducherry ---
  '600': { state: 'Tamil Nadu', defaultCity: 'Chennai', defaultDistrict: 'Chennai' },
  '601': { state: 'Tamil Nadu', defaultCity: 'Tiruvallur', defaultDistrict: 'Tiruvallur' },
  '602': { state: 'Tamil Nadu', defaultCity: 'Sriperumbudur', defaultDistrict: 'Kanchipuram' },
  '603': { state: 'Tamil Nadu', defaultCity: 'Chengalpattu', defaultDistrict: 'Chengalpattu' },
  '604': { state: 'Tamil Nadu', defaultCity: 'Tindivanam', defaultDistrict: 'Villupuram' },
  '605': { state: 'Puducherry', defaultCity: 'Puducherry', defaultDistrict: 'Puducherry' },
  '606': { state: 'Tamil Nadu', defaultCity: 'Tiruvannamalai', defaultDistrict: 'Tiruvannamalai' },
  '607': { state: 'Tamil Nadu', defaultCity: 'Cuddalore', defaultDistrict: 'Cuddalore' },
  '608': { state: 'Tamil Nadu', defaultCity: 'Chidambaram', defaultDistrict: 'Cuddalore' },
  '609': { state: 'Tamil Nadu', defaultCity: 'Mayiladuthurai', defaultDistrict: 'Mayiladuthurai' },
  '610': { state: 'Tamil Nadu', defaultCity: 'Tiruvarur', defaultDistrict: 'Tiruvarur' },
  '611': { state: 'Tamil Nadu', defaultCity: 'Nagapattinam', defaultDistrict: 'Nagapattinam' },
  '612': { state: 'Tamil Nadu', defaultCity: 'Kumbakonam', defaultDistrict: 'Thanjavur' },
  '613': { state: 'Tamil Nadu', defaultCity: 'Thanjavur', defaultDistrict: 'Thanjavur' },
  '614': { state: 'Tamil Nadu', defaultCity: 'Pattukkottai', defaultDistrict: 'Thanjavur' },
  '620': { state: 'Tamil Nadu', defaultCity: 'Tiruchirappalli', defaultDistrict: 'Tiruchirappalli' },
  '621': { state: 'Tamil Nadu', defaultCity: 'Perambalur', defaultDistrict: 'Perambalur' },
  '622': { state: 'Tamil Nadu', defaultCity: 'Pudukkottai', defaultDistrict: 'Pudukkottai' },
  '624': { state: 'Tamil Nadu', defaultCity: 'Dindigul', defaultDistrict: 'Dindigul' },
  '625': { state: 'Tamil Nadu', defaultCity: 'Madurai', defaultDistrict: 'Madurai' },
  '626': { state: 'Tamil Nadu', defaultCity: 'Virudhunagar', defaultDistrict: 'Virudhunagar' },
  '627': { state: 'Tamil Nadu', defaultCity: 'Tirunelveli', defaultDistrict: 'Tirunelveli' },
  '628': { state: 'Tamil Nadu', defaultCity: 'Thoothukudi', defaultDistrict: 'Thoothukudi' },
  '629': { state: 'Tamil Nadu', defaultCity: 'Nagercoil', defaultDistrict: 'Kanyakumari' },
  '630': { state: 'Tamil Nadu', defaultCity: 'Karaikudi', defaultDistrict: 'Sivaganga' },
  '631': { state: 'Tamil Nadu', defaultCity: 'Kanchipuram', defaultDistrict: 'Kanchipuram' },
  '632': { state: 'Tamil Nadu', defaultCity: 'Vellore', defaultDistrict: 'Vellore' },
  '635': { state: 'Tamil Nadu', defaultCity: 'Hosur', defaultDistrict: 'Krishnagiri' },
  '636': { state: 'Tamil Nadu', defaultCity: 'Salem', defaultDistrict: 'Salem' },
  '637': { state: 'Tamil Nadu', defaultCity: 'Namakkal', defaultDistrict: 'Namakkal' },
  '638': { state: 'Tamil Nadu', defaultCity: 'Erode', defaultDistrict: 'Erode' },
  '639': { state: 'Tamil Nadu', defaultCity: 'Karur', defaultDistrict: 'Karur' },
  '641': { state: 'Tamil Nadu', defaultCity: 'Coimbatore', defaultDistrict: 'Coimbatore' },
  '642': { state: 'Tamil Nadu', defaultCity: 'Pollachi', defaultDistrict: 'Coimbatore' },
  '643': { state: 'Tamil Nadu', defaultCity: 'Ooty', defaultDistrict: 'Nilgiris' },
  '670': { state: 'Kerala', defaultCity: 'Kannur', defaultDistrict: 'Kannur' },
  '671': { state: 'Kerala', defaultCity: 'Kasaragod', defaultDistrict: 'Kasaragod' },
  '673': { state: 'Kerala', defaultCity: 'Kozhikode', defaultDistrict: 'Kozhikode' },
  '676': { state: 'Kerala', defaultCity: 'Malappuram', defaultDistrict: 'Malappuram' },
  '678': { state: 'Kerala', defaultCity: 'Palakkad', defaultDistrict: 'Palakkad' },
  '679': { state: 'Kerala', defaultCity: 'Ottapalam', defaultDistrict: 'Palakkad' },
  '680': { state: 'Kerala', defaultCity: 'Thrissur', defaultDistrict: 'Thrissur' },
  '682': { state: 'Kerala', defaultCity: 'Kochi', defaultDistrict: 'Ernakulam' },
  '683': { state: 'Kerala', defaultCity: 'Aluva', defaultDistrict: 'Ernakulam' },
  '685': { state: 'Kerala', defaultCity: 'Painavu', defaultDistrict: 'Idukki' },
  '686': { state: 'Kerala', defaultCity: 'Kottayam', defaultDistrict: 'Kottayam' },
  '688': { state: 'Kerala', defaultCity: 'Alappuzha', defaultDistrict: 'Alappuzha' },
  '689': { state: 'Kerala', defaultCity: 'Pathanamthitta', defaultDistrict: 'Pathanamthitta' },
  '690': { state: 'Kerala', defaultCity: 'Kayamkulam', defaultDistrict: 'Alappuzha' },
  '691': { state: 'Kerala', defaultCity: 'Kollam', defaultDistrict: 'Kollam' },
  '695': { state: 'Kerala', defaultCity: 'Thiruvananthapuram', defaultDistrict: 'Thiruvananthapuram' },

  // --- ZONE 7: West Bengal, Odisha, Assam, NE States, Sikkim, Andaman & Nicobar ---
  '700': { state: 'West Bengal', defaultCity: 'Kolkata', defaultDistrict: 'Kolkata' },
  '711': { state: 'West Bengal', defaultCity: 'Howrah', defaultDistrict: 'Howrah' },
  '712': { state: 'West Bengal', defaultCity: 'Chinsurah', defaultDistrict: 'Hooghly' },
  '713': { state: 'West Bengal', defaultCity: 'Asansol', defaultDistrict: 'Paschim Bardhaman' },
  '721': { state: 'West Bengal', defaultCity: 'Medinipur', defaultDistrict: 'Paschim Medinipur' },
  '722': { state: 'West Bengal', defaultCity: 'Bankura', defaultDistrict: 'Bankura' },
  '723': { state: 'West Bengal', defaultCity: 'Purulia', defaultDistrict: 'Purulia' },
  '731': { state: 'West Bengal', defaultCity: 'Suri', defaultDistrict: 'Birbhum' },
  '732': { state: 'West Bengal', defaultCity: 'Malda', defaultDistrict: 'Malda' },
  '733': { state: 'West Bengal', defaultCity: 'Raiganj', defaultDistrict: 'Uttar Dinajpur' },
  '734': { state: 'West Bengal', defaultCity: 'Siliguri', defaultDistrict: 'Darjeeling' },
  '735': { state: 'West Bengal', defaultCity: 'Jalpaiguri', defaultDistrict: 'Jalpaiguri' },
  '736': { state: 'West Bengal', defaultCity: 'Cooch Behar', defaultDistrict: 'Cooch Behar' },
  '737': { state: 'Sikkim', defaultCity: 'Gangtok', defaultDistrict: 'East Sikkim' },
  '741': { state: 'West Bengal', defaultCity: 'Krishnanagar', defaultDistrict: 'Nadia' },
  '742': { state: 'West Bengal', defaultCity: 'Berhampore', defaultDistrict: 'Murshidabad' },
  '743': { state: 'West Bengal', defaultCity: 'Barasat', defaultDistrict: 'North 24 Parganas' },
  '744': { state: 'Andaman and Nicobar Islands', defaultCity: 'Port Blair', defaultDistrict: 'South Andaman' },
  '751': { state: 'Odisha', defaultCity: 'Bhubaneswar', defaultDistrict: 'Khordha' },
  '752': { state: 'Odisha', defaultCity: 'Puri', defaultDistrict: 'Puri' },
  '753': { state: 'Odisha', defaultCity: 'Cuttack', defaultDistrict: 'Cuttack' },
  '754': { state: 'Odisha', defaultCity: 'Kendrapara', defaultDistrict: 'Kendrapara' },
  '755': { state: 'Odisha', defaultCity: 'Jajpur', defaultDistrict: 'Jajpur' },
  '756': { state: 'Odisha', defaultCity: 'Balasore', defaultDistrict: 'Balasore' },
  '757': { state: 'Odisha', defaultCity: 'Baripada', defaultDistrict: 'Mayurbhanj' },
  '758': { state: 'Odisha', defaultCity: 'Kendujhar', defaultDistrict: 'Kendujhar' },
  '759': { state: 'Odisha', defaultCity: 'Dhenkanal', defaultDistrict: 'Dhenkanal' },
  '760': { state: 'Odisha', defaultCity: 'Berhampur', defaultDistrict: 'Ganjam' },
  '761': { state: 'Odisha', defaultCity: 'Chhatrapur', defaultDistrict: 'Ganjam' },
  '762': { state: 'Odisha', defaultCity: 'Phulbani', defaultDistrict: 'Kandhamal' },
  '764': { state: 'Odisha', defaultCity: 'Koraput', defaultDistrict: 'Koraput' },
  '765': { state: 'Odisha', defaultCity: 'Rayagada', defaultDistrict: 'Rayagada' },
  '766': { state: 'Odisha', defaultCity: 'Bhawanipatna', defaultDistrict: 'Kalahandi' },
  '767': { state: 'Odisha', defaultCity: 'Balangir', defaultDistrict: 'Balangir' },
  '768': { state: 'Odisha', defaultCity: 'Sambalpur', defaultDistrict: 'Sambalpur' },
  '769': { state: 'Odisha', defaultCity: 'Rourkela', defaultDistrict: 'Sundargarh' },
  '770': { state: 'Odisha', defaultCity: 'Sundargarh', defaultDistrict: 'Sundargarh' },
  '781': { state: 'Assam', defaultCity: 'Guwahati', defaultDistrict: 'Kamrup Metropolitan' },
  '782': { state: 'Assam', defaultCity: 'Nagaon', defaultDistrict: 'Nagaon' },
  '783': { state: 'Assam', defaultCity: 'Goalpara', defaultDistrict: 'Goalpara' },
  '784': { state: 'Assam', defaultCity: 'Tezpur', defaultDistrict: 'Sonitpur' },
  '785': { state: 'Assam', defaultCity: 'Jorhat', defaultDistrict: 'Jorhat' },
  '786': { state: 'Assam', defaultCity: 'Dibrugarh', defaultDistrict: 'Dibrugarh' },
  '787': { state: 'Assam', defaultCity: 'North Lakhimpur', defaultDistrict: 'Lakhimpur' },
  '788': { state: 'Assam', defaultCity: 'Silchar', defaultDistrict: 'Cachar' },
  '790': { state: 'Arunachal Pradesh', defaultCity: 'Tawang', defaultDistrict: 'Tawang' },
  '791': { state: 'Arunachal Pradesh', defaultCity: 'Itanagar', defaultDistrict: 'Papum Pare' },
  '792': { state: 'Arunachal Pradesh', defaultCity: 'Pasighat', defaultDistrict: 'East Siang' },
  '793': { state: 'Meghalaya', defaultCity: 'Shillong', defaultDistrict: 'East Khasi Hills' },
  '794': { state: 'Meghalaya', defaultCity: 'Tura', defaultDistrict: 'West Garo Hills' },
  '795': { state: 'Manipur', defaultCity: 'Imphal', defaultDistrict: 'Imphal East' },
  '796': { state: 'Mizoram', defaultCity: 'Aizawl', defaultDistrict: 'Aizawl' },
  '797': { state: 'Nagaland', defaultCity: 'Kohima', defaultDistrict: 'Kohima' },
  '798': { state: 'Nagaland', defaultCity: 'Mokokchung', defaultDistrict: 'Mokokchung' },
  '799': { state: 'Tripura', defaultCity: 'Agartala', defaultDistrict: 'West Tripura' },

  // --- ZONE 8: Bihar & Jharkhand ---
  '800': { state: 'Bihar', defaultCity: 'Patna', defaultDistrict: 'Patna' },
  '801': { state: 'Bihar', defaultCity: 'Danapur', defaultDistrict: 'Patna' },
  '802': { state: 'Bihar', defaultCity: 'Arrah', defaultDistrict: 'Bhojpur' },
  '803': { state: 'Bihar', defaultCity: 'Bihar Sharif', defaultDistrict: 'Nalanda' },
  '804': { state: 'Bihar', defaultCity: 'Jehanabad', defaultDistrict: 'Jehanabad' },
  '805': { state: 'Bihar', defaultCity: 'Nawada', defaultDistrict: 'Nawada' },
  '811': { state: 'Bihar', defaultCity: 'Munger', defaultDistrict: 'Munger' },
  '812': { state: 'Bihar', defaultCity: 'Bhagalpur', defaultDistrict: 'Bhagalpur' },
  '813': { state: 'Bihar', defaultCity: 'Banka', defaultDistrict: 'Banka' },
  '814': { state: 'Jharkhand', defaultCity: 'Deoghar', defaultDistrict: 'Deoghar' },
  '815': { state: 'Jharkhand', defaultCity: 'Giridih', defaultDistrict: 'Giridih' },
  '816': { state: 'Jharkhand', defaultCity: 'Dumka', defaultDistrict: 'Dumka' },
  '821': { state: 'Bihar', defaultCity: 'Sasaram', defaultDistrict: 'Rohtas' },
  '822': { state: 'Jharkhand', defaultCity: 'Medininagar', defaultDistrict: 'Palamu' },
  '823': { state: 'Bihar', defaultCity: 'Gaya', defaultDistrict: 'Gaya' },
  '824': { state: 'Bihar', defaultCity: 'Aurangabad', defaultDistrict: 'Aurangabad' },
  '825': { state: 'Jharkhand', defaultCity: 'Hazaribagh', defaultDistrict: 'Hazaribagh' },
  '826': { state: 'Jharkhand', defaultCity: 'Dhanbad', defaultDistrict: 'Dhanbad' },
  '827': { state: 'Jharkhand', defaultCity: 'Bokaro Steel City', defaultDistrict: 'Bokaro' },
  '828': { state: 'Jharkhand', defaultCity: 'Dhanbad Rural', defaultDistrict: 'Dhanbad' },
  '829': { state: 'Jharkhand', defaultCity: 'Ramgarh', defaultDistrict: 'Ramgarh' },
  '831': { state: 'Jharkhand', defaultCity: 'Jamshedpur', defaultDistrict: 'East Singhbhum' },
  '832': { state: 'Jharkhand', defaultCity: 'Ghatshila', defaultDistrict: 'East Singhbhum' },
  '833': { state: 'Jharkhand', defaultCity: 'Chaibasa', defaultDistrict: 'West Singhbhum' },
  '834': { state: 'Jharkhand', defaultCity: 'Ranchi', defaultDistrict: 'Ranchi' },
  '835': { state: 'Jharkhand', defaultCity: 'Khunti', defaultDistrict: 'Khunti' },
  '841': { state: 'Bihar', defaultCity: 'Chhapra', defaultDistrict: 'Saran' },
  '842': { state: 'Bihar', defaultCity: 'Muzaffarpur', defaultDistrict: 'Muzaffarpur' },
  '843': { state: 'Bihar', defaultCity: 'Sitamarhi', defaultDistrict: 'Sitamarhi' },
  '844': { state: 'Bihar', defaultCity: 'Hajipur', defaultDistrict: 'Vaishali' },
  '845': { state: 'Bihar', defaultCity: 'Motihari', defaultDistrict: 'East Champaran' },
  '846': { state: 'Bihar', defaultCity: 'Darbhanga', defaultDistrict: 'Darbhanga' },
  '847': { state: 'Bihar', defaultCity: 'Madhubani', defaultDistrict: 'Madhubani' },
  '848': { state: 'Bihar', defaultCity: 'Samastipur', defaultDistrict: 'Samastipur' },
  '851': { state: 'Bihar', defaultCity: 'Begusarai', defaultDistrict: 'Begusarai' },
  '852': { state: 'Bihar', defaultCity: 'Saharsa', defaultDistrict: 'Saharsa' },
  '853': { state: 'Bihar', defaultCity: 'Khagaria', defaultDistrict: 'Khagaria' },
  '854': { state: 'Bihar', defaultCity: 'Purnia', defaultDistrict: 'Purnia' },
  '855': { state: 'Bihar', defaultCity: 'Kishanganj', defaultDistrict: 'Kishanganj' },

  // --- ZONE 9: Army Postal Service ---
  '900': { state: 'Delhi', defaultCity: 'New Delhi', defaultDistrict: 'Army Postal Service' },
  '901': { state: 'Delhi', defaultCity: 'New Delhi', defaultDistrict: 'Army Postal Service' },
  '908': { state: 'Delhi', defaultCity: 'New Delhi', defaultDistrict: 'Army Postal Service' },
}

/**
 * 2-Digit Circle Prefix Map covering every circle across all 28 Indian states.
 */
export const POSTAL_CIRCLE_PREFIX_MAP: Record<string, PostalCircleRegion> = {
  '11': { state: 'Delhi', defaultCity: 'New Delhi', defaultDistrict: 'Central Delhi' },
  '12': { state: 'Haryana', defaultCity: 'Gurugram', defaultDistrict: 'Gurugram' },
  '13': { state: 'Haryana', defaultCity: 'Ambala', defaultDistrict: 'Ambala' },
  '14': { state: 'Punjab', defaultCity: 'Ludhiana', defaultDistrict: 'Ludhiana' },
  '15': { state: 'Punjab', defaultCity: 'Bathinda', defaultDistrict: 'Bathinda' },
  '16': { state: 'Chandigarh', defaultCity: 'Chandigarh', defaultDistrict: 'Chandigarh' },
  '17': { state: 'Himachal Pradesh', defaultCity: 'Shimla', defaultDistrict: 'Shimla' },
  '18': { state: 'Jammu and Kashmir', defaultCity: 'Jammu', defaultDistrict: 'Jammu' },
  '19': { state: 'Jammu and Kashmir', defaultCity: 'Srinagar', defaultDistrict: 'Srinagar' },
  '20': { state: 'Uttar Pradesh', defaultCity: 'Noida', defaultDistrict: 'Gautam Buddha Nagar' },
  '21': { state: 'Uttar Pradesh', defaultCity: 'Prayagraj', defaultDistrict: 'Prayagraj' },
  '22': { state: 'Uttar Pradesh', defaultCity: 'Lucknow', defaultDistrict: 'Lucknow' },
  '23': { state: 'Uttar Pradesh', defaultCity: 'Mirzapur', defaultDistrict: 'Mirzapur' },
  '24': { state: 'Uttarakhand', defaultCity: 'Dehradun', defaultDistrict: 'Dehradun' },
  '25': { state: 'Uttar Pradesh', defaultCity: 'Meerut', defaultDistrict: 'Meerut' },
  '26': { state: 'Uttarakhand', defaultCity: 'Haldwani', defaultDistrict: 'Nainital' },
  '27': { state: 'Uttar Pradesh', defaultCity: 'Gorakhpur', defaultDistrict: 'Gorakhpur' },
  '28': { state: 'Uttar Pradesh', defaultCity: 'Agra', defaultDistrict: 'Agra' },
  '30': { state: 'Rajasthan', defaultCity: 'Jaipur', defaultDistrict: 'Jaipur' },
  '31': { state: 'Rajasthan', defaultCity: 'Udaipur', defaultDistrict: 'Udaipur' },
  '32': { state: 'Rajasthan', defaultCity: 'Kota', defaultDistrict: 'Kota' },
  '33': { state: 'Rajasthan', defaultCity: 'Bikaner', defaultDistrict: 'Bikaner' },
  '34': { state: 'Rajasthan', defaultCity: 'Jodhpur', defaultDistrict: 'Jodhpur' },
  '36': { state: 'Gujarat', defaultCity: 'Rajkot', defaultDistrict: 'Rajkot' },
  '37': { state: 'Gujarat', defaultCity: 'Jamnagar', defaultDistrict: 'Jamnagar' },
  '38': { state: 'Gujarat', defaultCity: 'Ahmedabad', defaultDistrict: 'Ahmedabad' },
  '39': { state: 'Gujarat', defaultCity: 'Surat', defaultDistrict: 'Surat' },
  '40': { state: 'Maharashtra', defaultCity: 'Mumbai', defaultDistrict: 'Mumbai' },
  '41': { state: 'Maharashtra', defaultCity: 'Pune', defaultDistrict: 'Pune' },
  '42': { state: 'Maharashtra', defaultCity: 'Nashik', defaultDistrict: 'Nashik' },
  '43': { state: 'Maharashtra', defaultCity: 'Chhatrapati Sambhajinagar', defaultDistrict: 'Chhatrapati Sambhajinagar' },
  '44': { state: 'Maharashtra', defaultCity: 'Nagpur', defaultDistrict: 'Nagpur' },
  '45': { state: 'Madhya Pradesh', defaultCity: 'Indore', defaultDistrict: 'Indore' },
  '46': { state: 'Madhya Pradesh', defaultCity: 'Bhopal', defaultDistrict: 'Bhopal' },
  '47': { state: 'Madhya Pradesh', defaultCity: 'Gwalior', defaultDistrict: 'Gwalior' },
  '48': { state: 'Madhya Pradesh', defaultCity: 'Jabalpur', defaultDistrict: 'Jabalpur' },
  '49': { state: 'Chhattisgarh', defaultCity: 'Raipur', defaultDistrict: 'Raipur' },
  '50': { state: 'Telangana', defaultCity: 'Hyderabad', defaultDistrict: 'Hyderabad' },
  '51': { state: 'Andhra Pradesh', defaultCity: 'Tirupati', defaultDistrict: 'Tirupati' },
  '52': { state: 'Andhra Pradesh', defaultCity: 'Vijayawada', defaultDistrict: 'Krishna' },
  '53': { state: 'Andhra Pradesh', defaultCity: 'Visakhapatnam', defaultDistrict: 'Visakhapatnam' },
  '56': { state: 'Karnataka', defaultCity: 'Bengaluru', defaultDistrict: 'Bengaluru Urban' },
  '57': { state: 'Karnataka', defaultCity: 'Mangaluru', defaultDistrict: 'Dakshina Kannada' },
  '58': { state: 'Karnataka', defaultCity: 'Hubballi', defaultDistrict: 'Dharwad' },
  '59': { state: 'Karnataka', defaultCity: 'Belagavi', defaultDistrict: 'Belagavi' },
  '60': { state: 'Tamil Nadu', defaultCity: 'Chennai', defaultDistrict: 'Chennai' },
  '61': { state: 'Tamil Nadu', defaultCity: 'Thanjavur', defaultDistrict: 'Thanjavur' },
  '62': { state: 'Tamil Nadu', defaultCity: 'Madurai', defaultDistrict: 'Madurai' },
  '63': { state: 'Tamil Nadu', defaultCity: 'Coimbatore', defaultDistrict: 'Coimbatore' },
  '64': { state: 'Tamil Nadu', defaultCity: 'Coimbatore', defaultDistrict: 'Coimbatore' },
  '67': { state: 'Kerala', defaultCity: 'Kozhikode', defaultDistrict: 'Kozhikode' },
  '68': { state: 'Kerala', defaultCity: 'Kochi', defaultDistrict: 'Ernakulam' },
  '69': { state: 'Kerala', defaultCity: 'Thiruvananthapuram', defaultDistrict: 'Thiruvananthapuram' },
  '70': { state: 'West Bengal', defaultCity: 'Kolkata', defaultDistrict: 'Kolkata' },
  '71': { state: 'West Bengal', defaultCity: 'Howrah', defaultDistrict: 'Howrah' },
  '72': { state: 'West Bengal', defaultCity: 'Kharagpur', defaultDistrict: 'Paschim Medinipur' },
  '73': { state: 'West Bengal', defaultCity: 'Siliguri', defaultDistrict: 'Darjeeling' },
  '74': { state: 'Andaman and Nicobar Islands', defaultCity: 'Port Blair', defaultDistrict: 'South Andaman' },
  '75': { state: 'Odisha', defaultCity: 'Bhubaneswar', defaultDistrict: 'Khordha' },
  '76': { state: 'Odisha', defaultCity: 'Cuttack', defaultDistrict: 'Cuttack' },
  '77': { state: 'Odisha', defaultCity: 'Sambalpur', defaultDistrict: 'Sambalpur' },
  '78': { state: 'Assam', defaultCity: 'Guwahati', defaultDistrict: 'Kamrup Metropolitan' },
  '79': { state: 'Meghalaya', defaultCity: 'Shillong', defaultDistrict: 'East Khasi Hills' },
  '80': { state: 'Bihar', defaultCity: 'Patna', defaultDistrict: 'Patna' },
  '81': { state: 'Bihar', defaultCity: 'Bhagalpur', defaultDistrict: 'Bhagalpur' },
  '82': { state: 'Bihar', defaultCity: 'Gaya', defaultDistrict: 'Gaya' },
  '83': { state: 'Jharkhand', defaultCity: 'Ranchi', defaultDistrict: 'Ranchi' },
  '84': { state: 'Bihar', defaultCity: 'Muzaffarpur', defaultDistrict: 'Muzaffarpur' },
  '85': { state: 'Bihar', defaultCity: 'Darbhanga', defaultDistrict: 'Darbhanga' },
}

/**
 * 1-Digit Postal Zone safety net fallback ensuring that any valid 6-digit PIN
 * maps to a valid state in that geographical region.
 */
export const POSTAL_ZONE_1DIGIT_MAP: Record<string, PostalCircleRegion> = {
  '1': { state: 'Delhi', defaultCity: 'New Delhi', defaultDistrict: 'Central Delhi' },
  '2': { state: 'Uttar Pradesh', defaultCity: 'Lucknow', defaultDistrict: 'Lucknow' },
  '3': { state: 'Gujarat', defaultCity: 'Ahmedabad', defaultDistrict: 'Ahmedabad' },
  '4': { state: 'Maharashtra', defaultCity: 'Mumbai', defaultDistrict: 'Mumbai' },
  '5': { state: 'Telangana', defaultCity: 'Hyderabad', defaultDistrict: 'Hyderabad' },
  '6': { state: 'Tamil Nadu', defaultCity: 'Chennai', defaultDistrict: 'Chennai' },
  '7': { state: 'West Bengal', defaultCity: 'Kolkata', defaultDistrict: 'Kolkata' },
  '8': { state: 'Bihar', defaultCity: 'Patna', defaultDistrict: 'Patna' },
  '9': { state: 'Delhi', defaultCity: 'New Delhi', defaultDistrict: 'Army Postal Service' },
}

/**
 * Pure functional hierarchical resolver for any 6-digit Indian PIN code.
 * 1. Special 6-digit enclaves / islands (Lakshadweep, DNH & Daman & Diu, Puducherry)
 * 2. 3-digit sub-region / UT (Ladakh, Goa, Sikkim, Arunachal, Manipur, Mizoram, Nagaland, Tripura, Meghalaya, etc.)
 * 3. 2-digit circle
 * 4. 1-digit zone safety net
 */
export const resolvePostalCircle = (pincode: string): PostalCircleRegion | null => {
  const clean = pincode.replace(/\D/g, '')
  if (clean.length !== 6) return null

  // 1. Exact enclave / island check
  const special = SPECIAL_UT_PINCODE_MAP[clean]
  if (special) return special

  // Lakshadweep pattern (68255x)
  if (clean.startsWith('68255')) {
    return { state: 'Lakshadweep', defaultCity: 'Kavaratti', defaultDistrict: 'Lakshadweep' }
  }

  // 2. 3-digit prefix lookup
  const prefix3 = clean.slice(0, 3)
  const subRegion = SUB_REGION_3DIGIT_PREFIX_MAP[prefix3]
  if (subRegion) return subRegion

  // 3. 2-digit circle lookup
  const prefix2 = clean.slice(0, 2)
  const circle = POSTAL_CIRCLE_PREFIX_MAP[prefix2]
  if (circle) return circle

  // 4. 1-digit zone fallback
  const prefix1 = clean.slice(0, 1)
  return POSTAL_ZONE_1DIGIT_MAP[prefix1] || null
}

